SELECT H.HACKER_ID, H.NAME, SUM(S.SCORE)
  FROM HACKERS H, (SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS SCORE
                     FROM SUBMISSIONS
                    GROUP BY HACKER_ID, CHALLENGE_ID) AS S
 WHERE H.HACKER_ID = S.HACKER_ID
 GROUP BY H.HACKER_ID, H.NAME
 HAVING SUM(S.SCORE) <> 0
  ORDER BY 3 DESC, 1;

---------------------------------

WITH MAX_SCORE AS (
    SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE)
      FROM SUBIMISSIONS
     GROUP BY HACKER_ID, CHALLENGE_ID 
)
SELECT M.HACKER_ID, H.NAME, SUM(M.SCORE)
  FROM MAX_SCORE M INNER JOIN HACKERS H ON M.HACKER_ID = H.HACKER_ID
 GROUP BY M.HACKER_ID, H.NAME
HAVING M.SCORE > 0;