DELIMITER $$
CREATE PROCEDURE PRINT_TRIANGLE(IN I INT)
BEGIN
    WHILE I > 0 DO
        SELECT IF(I = 1, '*', REPEAT('* ', I));
        SET I = I - 1;
    END WHILE;
END$$
DELIMITER ;

CALL PRINT_TRIANGLE(20);