DELIMITER $$

CREATE PROCEDURE PRINT_TRIANGULE(IN N INT)
BEGIN
    DECLARE I INT DEFAULT 1;
    WHILE I <= N DO
        SELECT REPEAT('* ', I);
        SET I = I + 1;
    END WHILE;
END$$

DELIMITER ;

CALL PRINT_TRIANGULE(20);
