SELECT *
  FROM (SELECT CITY, LENGTH(CITY)
         FROM STATION
        ORDER BY LENGTH(CITY), CITY LIMIT 1) AS BIGEST
UNION
SELECT *
  FROM (SELECT CITY, LENGTH(CITY)
          FROM STATION
         ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1) AS SMALEST