SELECT H.HACKER_ID,
       H.NAME
  FROM HACKERS AS H,
       SUBMISSIONS AS S,
       CHALLENGES AS C,
       DIFFICULTY AS D
 WHERE H.HACKER_ID = S.HACKER_ID
   AND S.CHALLENGE_ID = C.CHALLENGE_ID
   AND C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
   AND S.SCORE = D.SCORE
 GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(1) > 1
 ORDER BY COUNT(1) DESC, H.HACKER_ID;

---------

--SELECT H.HACKER_ID,
--       H.NAME
--  FROM HACKERS H
--  JOIN SUBMISSIONS S ON H.HACKER_ID = S.HACKER_ID
--  JOIN CHALLENGES C ON S.CHALLENGE_ID = C.CHALLENGE_ID
--  JOIN DIFFICULTY D ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
-- WHERE S.SCORE = D.SCORE
-- GROUP BY H.HACKER_ID, H.NAME
--HAVING COUNT(DISTINCT C.CHALLENGE_ID) > 1
-- ORDER BY COUNT(DISTINCT C.CHALLENGE_ID) DESC, H.HACKER_ID;