SELECT H.HACKER_ID,
       H.NAME
  FROM HACKERS AS H,
       SUBMISSIONS S,
       CHALLENGES C,
       DIFFICULTY D
 WHERE H.HACKER_ID = S.HACKER_ID
   AND S.CHALLENGE_ID = C.CHALLENGE_ID
   AND C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
   AND S.SCORE = D.SCORE
 GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(1) > 1
 ORDER BY COUNT(1) DESC, H.HACKER_ID;