WITH CTE1 AS (
    SELECT START_DATE,
           ROW_NUMBER() OVER (ORDER BY START_DATE) AS RN
    FROM PROJECTS
    WHERE START_DATE NOT IN (SELECT END_DATE FROM PROJECTS) 
),
CTE2 AS (
    SELECT END_DATE,
           ROW_NUMBER() OVER (ORDER BY END_DATE) AS RN
    FROM PROJECTS
    WHERE END_DATE NOT IN (SELECT START_DATE FROM PROJECTS)
)
SELECT CTE1.START_DATE,
       CTE2.END_DATE
  FROM CTE1 JOIN CTE2 ON CTE1.RN = CTE2.RN
 ORDER BY DATEDIFF(CTE2.END_DATE, CTE1.START_DATE), CTE1.START_DATE;