WITH BEST_FRIENDS_SALARY AS (
    SELECT S.ID, P.SALARY
      FROM STUDENTS S JOIN FRIENDS F ON S.ID = F.ID, PACKAGES P
     WHERE F.FRIEND_ID = P.ID
)
SELECT S.NAME
  FROM STUDENTS S JOIN BEST_FRIENDS_SALARY B ON S.ID = B.ID
  JOIN PACKAGES P ON S.ID = P.ID
 WHERE P.SALARY < B.SALARY
 ORDER BY B.SALARY;