SELECT C.CONTEST_ID,
       C.HACKER_ID,
       C.NAME,
       TOTAL_SUBMIT.SUM_TS,
       TOTAL_SUBMIT.SUM_TAS,
       TOTAL_VIEW.SUM_TV,
       TOTAL_VIEW.SUM_TUV
  FROM CONTESTS C,
       (SELECT CL.CONTEST_ID,
               SUM(SS.TOTAL_SUBMISSIONS) as SUM_TS,
               SUM(SS.TOTAL_ACCEPTED_SUBMISSIONS) as SUM_TAS
          FROM COLLEGES CL
         INNER JOIN CHALLENGES CH ON CH.COLLEGE_ID = CL.COLLEGE_ID
         INNER JOIN SUBMISSION_STATS SS ON CH.CHALLENGE_ID = SS.CHALLENGE_ID
         GROUP BY CL.CONTEST_ID) AS TOTAL_SUBMIT,
       (SELECT CL.CONTEST_ID,
               SUM(VS.TOTAL_VIEWS) AS SUM_TV,
               SUM(VS.TOTAL_UNIQUE_VIEWS) AS SUM_TUV
          FROM COLLEGES CL
         INNER JOIN CHALLENGES CH ON CH.COLLEGE_ID = CL.COLLEGE_ID
         INNER JOIN VIEW_STATS VS ON CH.CHALLENGE_ID = VS.CHALLENGE_ID
         GROUP BY CL.CONTEST_ID) AS TOTAL_VIEW
 WHERE C.CONTEST_ID = TOTAL_SUBMIT.CONTEST_ID
   AND C.CONTEST_ID = TOTAL_VIEW.CONTEST_ID
   AND (TOTAL_SUBMIT.SUM_TS > 0 OR TOTAL_SUBMIT.SUM_TAS > 0 OR TOTAL_VIEW.SUM_TV > 0 OR TOTAL_VIEW.SUM_TUV > 0)
 ORDER BY C.CONTEST_ID;